spring:
  datasource:
    url: jdbc:oracle:thin:@//ora4.ii.pw.edu.pl:1521/pdb1.ii.pw.edu.pl
    username: yharbar
    password: yharbar
  sql:
    init:
      data-locations: classpath:insert_data.sql
      mode: always
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
